name: Build Jenkins Sidecar

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - uses: actions/upload-artifact@v3
        with:
          name: jenkins-sidecar-1.0-SNAPSHOT-jar-with-dependencies.jar
          path: target/jenkins-sidecar-1.0-SNAPSHOT-jar-with-dependencies.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/jenkins-sidecar-1.0-SNAPSHOT-jar-with-dependencies.jar